### ISSUE TITLE
duplication not working

### ISSUE THREAD

**Issue by Metis77** [codefog/contao-news_categories#102]
```
Fatal error: Uncaught exception Exception with message Query error: Column 'alias' cannot be null (INSERT INTO tl_news_category (pid, sorting, tstamp, title, frontendTitle, alias, cssClass, hideInList, hideInReader, excludeInRelated, jumpTo, published) VALUES (2, 128, 0, 'b (Kopie)', '', NULL, '', '', '', '', '0', '')) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/drivers/DC_Table.php(977): Contao\Database\Statement->execute()
#2 system/modules/core/classes/Backend.php(650): Contao\DC_Table->copy()
#3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('news')
#4 contao/main.php(20): Contao\BackendMain->run()
#5 {main}
```

If you duplicate a news category and than want to insert, you get the above error, as no alias is there.
So duplicating does not work, only add new.

**Comment by qzminski** [comment]
Hmm I can't reproduce that. Can you show me on a real-world example what are you trying to do exactly?

**Comment by Metis77** [comment]
I can reproduce it here:
http://contao.derhaeuptling.com/contao/

**Comment by qzminski** [comment]
Can you update the website to the latest LTS please?

**Comment by Metis77** [comment]
After updating to Contao 3.5.27 this issue is gone. THX
